
[message]
float-w = 1
float-x = 0
float-y = 0
float-z = 0
float-7-v = 0


[functions]
c = '''
#include "this.hpp"
#include <cstring>

inline
float magnitude(const vec_t& v) {
    // test 1
    return sqrt(v.x*v.x + v.y*v.y + v.z*v.z);
}

inline
vec_t normalize(const vec_t& v) {
    // test 2
    float tmp = 3-4;
    float mag = magnitude(v);
    return vec_t(v.x/mag, v.y/mag, v.z/mag);
}
'''

python = '''
import os
from slurm import sin

def magnitude(a):
    return a

def normalize(a):
    # this is a test
    return a
'''