[global]
comments = '''
this is a global comment
'''
namespace = "test"

[license]
type = "MIT"
name = "bad bart"
year = 1997

[libraries]
c = ["<cmath>","<cstdint>",'"string.h"',"<cmath>","<cstdint>"]
python = [
    "from math import sqrt"
    ]

[message]
float-x = 0.0
float-y = 0.0
float-z = 0.0

comments = '''
x,y,z values of a vector, default is (0,0,0)
multiple lines
in this comment
'''

id = 1

[functions]
c = '''
inline
float magnitude(const vec_t& v) {
    // test 1
    return sqrt(v.x*v.x + v.y*v.y + v.z*v.z);
}

inline
vec_t normalize(const vec_t& v) {
    // test 2
    float tmp = 3-4;
    float mag = magnitude(v);
    return vec_t(v.x/mag, v.y/mag, v.z/mag);
}
'''

python = '''
def magnitude(a):
    return a

def normalize(a):
    # this is a test
    return a
'''

[serialize]
yivo = true
mavlink = false


