# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: covariance.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'covariance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ovariance.proto\x12\x05kevin\"1\n\x0b\x43ovariance3\x12\n\n\x02xx\x18\x01 \x01(\x01\x12\n\n\x02yy\x18\x02 \x01(\x01\x12\n\n\x02zz\x18\x03 \x01(\x01\"U\n\x0b\x43ovariance6\x12\n\n\x02xx\x18\x01 \x01(\x01\x12\n\n\x02yy\x18\x02 \x01(\x01\x12\n\n\x02zz\x18\x03 \x01(\x01\x12\n\n\x02xy\x18\x04 \x01(\x01\x12\n\n\x02xz\x18\x05 \x01(\x01\x12\n\n\x02yz\x18\x06 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'covariance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COVARIANCE3']._serialized_start=27
  _globals['_COVARIANCE3']._serialized_end=76
  _globals['_COVARIANCE6']._serialized_start=78
  _globals['_COVARIANCE6']._serialized_end=163
# @@protoc_insertion_point(module_scope)
