# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imu.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'imu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vector3_pb2 as vector3__pb2
import quaternion_pb2 as quaternion__pb2
import header_pb2 as header__pb2
import covariance_pb2 as covariance__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\timu.proto\x12\x05kevin\x1a\rvector3.proto\x1a\x10quaternion.proto\x1a\x0cheader.proto\x1a\x10\x63ovariance.proto\"\xf2\x01\n\x03Imu\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.kevin.Header\x12+\n\x13linear_acceleration\x18\x02 \x01(\x0b\x32\x0e.kevin.Vector3\x12(\n\x10\x61ngular_velocity\x18\x03 \x01(\x0b\x32\x0e.kevin.Vector3\x12&\n\x0borientation\x18\x04 \x01(\x0b\x32\x11.kevin.Quaternion\x12&\n\x0emagnetic_field\x18\x05 \x01(\x0b\x32\x0e.kevin.Vector3\x12\x10\n\x08pressure\x18\x06 \x01(\x01\x12\x13\n\x0btemperature\x18\x07 \x01(\x01\"{\n\x07ImuInfo\x12%\n\taccel_cov\x18\x01 \x01(\x0b\x32\x12.kevin.Covariance6\x12$\n\x08gyro_cov\x18\x02 \x01(\x0b\x32\x12.kevin.Covariance6\x12#\n\x07mag_cov\x18\x03 \x01(\x0b\x32\x12.kevin.Covariance6b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMU']._serialized_start=86
  _globals['_IMU']._serialized_end=328
  _globals['_IMUINFO']._serialized_start=330
  _globals['_IMUINFO']._serialized_end=453
# @@protoc_insertion_point(module_scope)
