# Do not edit, this is autogenerated
#
# The MIT License (MIT)
# Copyright (c) 2023 Kevin Walchko
# see LICENSE for full details
###############################################################################
from dataclasses import dataclass
from .base import Base
from .vec_t import vec_t
from .quat_t import quat_t
@dataclass
class pose_t(Base):
    position: list[vec_t] = field(default_factory=(lambda:[0, 0, 0]))
    orientation: list[quat_t] = field(default_factory=(lambda:[1, 0, 0, 0]))

    def __yivo__(self):
        # (fmt, size, id)
        return ("7f", 28, 5)

