# Do not edit, this is autogenerated
#
# The MIT License (MIT)
# Copyright (c) 2023 Kevin Walchko
# see LICENSE for full details
###############################################################################
from dataclasses import dataclass
from .base import Base
from .vec_t import vec_t
@dataclass
class twist_t(Base):
    linear: vec_t
    angular: vec_t

    def __yivo__(self):
        # (fmt, size, id)
        return ("6f", 24, 3)

