// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: range.proto
// Protobuf C++ Version: 5.29.3

#ifndef range_2eproto_2epb_2eh
#define range_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "header.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_range_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_range_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_range_2eproto;
namespace kevin {
class Range;
struct RangeDefaultTypeInternal;
extern RangeDefaultTypeInternal _Range_default_instance_;
}  // namespace kevin
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace kevin {
enum RangeType : int {
  ULTRASOUND = 0,
  INFRARED = 1,
  RangeType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  RangeType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool RangeType_IsValid(int value);
extern const uint32_t RangeType_internal_data_[];
constexpr RangeType RangeType_MIN = static_cast<RangeType>(0);
constexpr RangeType RangeType_MAX = static_cast<RangeType>(1);
constexpr int RangeType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
RangeType_descriptor();
template <typename T>
const std::string& RangeType_Name(T value) {
  static_assert(std::is_same<T, RangeType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RangeType_Name().");
  return RangeType_Name(static_cast<RangeType>(value));
}
template <>
inline const std::string& RangeType_Name(RangeType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RangeType_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool RangeType_Parse(absl::string_view name, RangeType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RangeType>(
      RangeType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Range final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kevin.Range) */ {
 public:
  inline Range() : Range(nullptr) {}
  ~Range() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Range* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Range));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Range(
      ::google::protobuf::internal::ConstantInitialized);

  inline Range(const Range& from) : Range(nullptr, from) {}
  inline Range(Range&& from) noexcept
      : Range(nullptr, std::move(from)) {}
  inline Range& operator=(const Range& from) {
    CopyFrom(from);
    return *this;
  }
  inline Range& operator=(Range&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Range& default_instance() {
    return *internal_default_instance();
  }
  static inline const Range* internal_default_instance() {
    return reinterpret_cast<const Range*>(
        &_Range_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Range& a, Range& b) { a.Swap(&b); }
  inline void Swap(Range* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Range* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Range* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Range>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Range& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Range& from) { Range::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Range* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kevin.Range"; }

 protected:
  explicit Range(::google::protobuf::Arena* arena);
  Range(::google::protobuf::Arena* arena, const Range& from);
  Range(::google::protobuf::Arena* arena, Range&& from) noexcept
      : Range(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHeaderFieldNumber = 1,
    kRadiationTypeFieldNumber = 2,
    kFieldOfViewFieldNumber = 3,
    kMinRangeFieldNumber = 4,
    kMaxRangeFieldNumber = 5,
    kRangeFieldNumber = 6,
    kVarianceFieldNumber = 7,
  };
  // .kevin.Header header = 1;
  bool has_header() const;
  void clear_header() ;
  const ::kevin::Header& header() const;
  PROTOBUF_NODISCARD ::kevin::Header* release_header();
  ::kevin::Header* mutable_header();
  void set_allocated_header(::kevin::Header* value);
  void unsafe_arena_set_allocated_header(::kevin::Header* value);
  ::kevin::Header* unsafe_arena_release_header();

  private:
  const ::kevin::Header& _internal_header() const;
  ::kevin::Header* _internal_mutable_header();

  public:
  // .kevin.RangeType radiation_type = 2;
  void clear_radiation_type() ;
  ::kevin::RangeType radiation_type() const;
  void set_radiation_type(::kevin::RangeType value);

  private:
  ::kevin::RangeType _internal_radiation_type() const;
  void _internal_set_radiation_type(::kevin::RangeType value);

  public:
  // float field_of_view = 3;
  void clear_field_of_view() ;
  float field_of_view() const;
  void set_field_of_view(float value);

  private:
  float _internal_field_of_view() const;
  void _internal_set_field_of_view(float value);

  public:
  // float min_range = 4;
  void clear_min_range() ;
  float min_range() const;
  void set_min_range(float value);

  private:
  float _internal_min_range() const;
  void _internal_set_min_range(float value);

  public:
  // float max_range = 5;
  void clear_max_range() ;
  float max_range() const;
  void set_max_range(float value);

  private:
  float _internal_max_range() const;
  void _internal_set_max_range(float value);

  public:
  // float range = 6;
  void clear_range() ;
  float range() const;
  void set_range(float value);

  private:
  float _internal_range() const;
  void _internal_set_range(float value);

  public:
  // float variance = 7;
  void clear_variance() ;
  float variance() const;
  void set_variance(float value);

  private:
  float _internal_variance() const;
  void _internal_set_variance(float value);

  public:
  // @@protoc_insertion_point(class_scope:kevin.Range)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Range& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::kevin::Header* header_;
    int radiation_type_;
    float field_of_view_;
    float min_range_;
    float max_range_;
    float range_;
    float variance_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_range_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Range

// .kevin.Header header = 1;
inline bool Range::has_header() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.header_ != nullptr);
  return value;
}
inline const ::kevin::Header& Range::_internal_header() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::kevin::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::kevin::Header&>(::kevin::_Header_default_instance_);
}
inline const ::kevin::Header& Range::header() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kevin.Range.header)
  return _internal_header();
}
inline void Range::unsafe_arena_set_allocated_header(::kevin::Header* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = reinterpret_cast<::kevin::Header*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kevin.Range.header)
}
inline ::kevin::Header* Range::release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kevin::Header* released = _impl_.header_;
  _impl_.header_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::kevin::Header* Range::unsafe_arena_release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kevin.Range.header)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kevin::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::kevin::Header* Range::_internal_mutable_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.header_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::kevin::Header>(GetArena());
    _impl_.header_ = reinterpret_cast<::kevin::Header*>(p);
  }
  return _impl_.header_;
}
inline ::kevin::Header* Range::mutable_header() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::kevin::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:kevin.Range.header)
  return _msg;
}
inline void Range::set_allocated_header(::kevin::Header* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.header_ = reinterpret_cast<::kevin::Header*>(value);
  // @@protoc_insertion_point(field_set_allocated:kevin.Range.header)
}

// .kevin.RangeType radiation_type = 2;
inline void Range::clear_radiation_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.radiation_type_ = 0;
}
inline ::kevin::RangeType Range::radiation_type() const {
  // @@protoc_insertion_point(field_get:kevin.Range.radiation_type)
  return _internal_radiation_type();
}
inline void Range::set_radiation_type(::kevin::RangeType value) {
  _internal_set_radiation_type(value);
  // @@protoc_insertion_point(field_set:kevin.Range.radiation_type)
}
inline ::kevin::RangeType Range::_internal_radiation_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::kevin::RangeType>(_impl_.radiation_type_);
}
inline void Range::_internal_set_radiation_type(::kevin::RangeType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.radiation_type_ = value;
}

// float field_of_view = 3;
inline void Range::clear_field_of_view() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field_of_view_ = 0;
}
inline float Range::field_of_view() const {
  // @@protoc_insertion_point(field_get:kevin.Range.field_of_view)
  return _internal_field_of_view();
}
inline void Range::set_field_of_view(float value) {
  _internal_set_field_of_view(value);
  // @@protoc_insertion_point(field_set:kevin.Range.field_of_view)
}
inline float Range::_internal_field_of_view() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.field_of_view_;
}
inline void Range::_internal_set_field_of_view(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field_of_view_ = value;
}

// float min_range = 4;
inline void Range::clear_min_range() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_range_ = 0;
}
inline float Range::min_range() const {
  // @@protoc_insertion_point(field_get:kevin.Range.min_range)
  return _internal_min_range();
}
inline void Range::set_min_range(float value) {
  _internal_set_min_range(value);
  // @@protoc_insertion_point(field_set:kevin.Range.min_range)
}
inline float Range::_internal_min_range() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.min_range_;
}
inline void Range::_internal_set_min_range(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_range_ = value;
}

// float max_range = 5;
inline void Range::clear_max_range() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_range_ = 0;
}
inline float Range::max_range() const {
  // @@protoc_insertion_point(field_get:kevin.Range.max_range)
  return _internal_max_range();
}
inline void Range::set_max_range(float value) {
  _internal_set_max_range(value);
  // @@protoc_insertion_point(field_set:kevin.Range.max_range)
}
inline float Range::_internal_max_range() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_range_;
}
inline void Range::_internal_set_max_range(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_range_ = value;
}

// float range = 6;
inline void Range::clear_range() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.range_ = 0;
}
inline float Range::range() const {
  // @@protoc_insertion_point(field_get:kevin.Range.range)
  return _internal_range();
}
inline void Range::set_range(float value) {
  _internal_set_range(value);
  // @@protoc_insertion_point(field_set:kevin.Range.range)
}
inline float Range::_internal_range() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.range_;
}
inline void Range::_internal_set_range(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.range_ = value;
}

// float variance = 7;
inline void Range::clear_variance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.variance_ = 0;
}
inline float Range::variance() const {
  // @@protoc_insertion_point(field_get:kevin.Range.variance)
  return _internal_variance();
}
inline void Range::set_variance(float value) {
  _internal_set_variance(value);
  // @@protoc_insertion_point(field_set:kevin.Range.variance)
}
inline float Range::_internal_variance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.variance_;
}
inline void Range::_internal_set_variance(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.variance_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace kevin


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::kevin::RangeType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::kevin::RangeType>() {
  return ::kevin::RangeType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // range_2eproto_2epb_2eh
