# Do not edit, this is autogenerated
# MIT Kevin Walchko (c) 2023
from dataclasses import dataclass

from vec import *


@dataclass(frozen=True)
class imu_t(Base):
    accel: vec_t # size: 12
    gyro: vec_t # size: 12
    mag: vec_t # size: 12
    pressure: float # size: 4
    temperature: float # size: 4
    error: int # size: 4
    timestamp: int # size: 4

    def __yivo__(self):
        # (fmt, size, name, id)
        return ("fffffffffffII", 52, imu_t, 4)