# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera_msgs.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'camera_msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import standard_msgs_pb2 as standard__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61mera_msgs.proto\x12\x05kevin\x1a\x13standard_msgs.proto\"O\n\x0fImageCompressed\x12\x1e\n\x07heading\x18\x01 \x01(\x0b\x32\r.kevin.Header\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\"v\n\x08ImageRaw\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.kevin.Header\x12\r\n\x05width\x18\x02 \x01(\x07\x12\x0e\n\x06height\x18\x03 \x01(\x07\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x0c\n\x04step\x18\x05 \x01(\x07\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\"\x86\x01\n\tStereoRaw\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.kevin.Header\x12\r\n\x05width\x18\x02 \x01(\x07\x12\x0e\n\x06height\x18\x03 \x01(\x07\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x0c\n\x04step\x18\x05 \x01(\x07\x12\x0c\n\x04left\x18\x06 \x01(\x0c\x12\r\n\x05right\x18\x07 \x01(\x0c\"\x97\x01\n\x11\x43\x61meraCalibration\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.kevin.Header\x12\r\n\x05width\x18\x02 \x01(\x07\x12\x0e\n\x06height\x18\x03 \x01(\x07\x12\x18\n\x10\x64istortion_model\x18\x04 \x01(\t\x12\t\n\x01\x44\x18\x05 \x03(\x01\x12\t\n\x01K\x18\x06 \x03(\x01\x12\t\n\x01R\x18\x07 \x03(\x01\x12\t\n\x01P\x18\x08 \x03(\x01\"\xa4\x01\n\x0e\x44isparityImage\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.kevin.Header\x12\x1e\n\x05image\x18\x02 \x01(\x0b\x32\x0f.kevin.ImageRaw\x12\t\n\x01\x66\x18\x03 \x01(\x02\x12\t\n\x01t\x18\x04 \x01(\x02\x12\x15\n\rmin_disparity\x18\x05 \x01(\x02\x12\x15\n\rmax_disparity\x18\x06 \x01(\x02\x12\x0f\n\x07\x64\x65lta_d\x18\x07 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGECOMPRESSED']._serialized_start=49
  _globals['_IMAGECOMPRESSED']._serialized_end=128
  _globals['_IMAGERAW']._serialized_start=130
  _globals['_IMAGERAW']._serialized_end=248
  _globals['_STEREORAW']._serialized_start=251
  _globals['_STEREORAW']._serialized_end=385
  _globals['_CAMERACALIBRATION']._serialized_start=388
  _globals['_CAMERACALIBRATION']._serialized_end=539
  _globals['_DISPARITYIMAGE']._serialized_start=542
  _globals['_DISPARITYIMAGE']._serialized_end=706
# @@protoc_insertion_point(module_scope)
