# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: range.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'range.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brange.proto\x12\x05kevin\x1a\x0cheader.proto\"\xae\x01\n\x05Range\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.kevin.Header\x12(\n\x0eradiation_type\x18\x02 \x01(\x0e\x32\x10.kevin.RangeType\x12\x15\n\rfield_of_view\x18\x03 \x01(\x02\x12\x11\n\tmin_range\x18\x04 \x01(\x02\x12\x11\n\tmax_range\x18\x05 \x01(\x02\x12\r\n\x05range\x18\x06 \x01(\x02\x12\x10\n\x08variance\x18\x07 \x01(\x02*4\n\tRangeType\x12\x0e\n\nULTRASOUND\x10\x00\x12\x0c\n\x08INFRARED\x10\x01\x12\t\n\x05LASER\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'range_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANGETYPE']._serialized_start=213
  _globals['_RANGETYPE']._serialized_end=265
  _globals['_RANGE']._serialized_start=37
  _globals['_RANGE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
