# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: satnav.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'satnav.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import covariance_pb2 as covariance__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csatnav.proto\x12\x05kevin\x1a\x0cheader.proto\x1a\x10\x63ovariance.proto\"U\n\x0cNavSatStatus\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.kevin.StatusFix\x12#\n\x07service\x18\x02 \x01(\x0e\x32\x12.kevin.ServiceType\"\xdd\x01\n\x06SatNav\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.kevin.Header\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.kevin.NavSatStatus\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x01\x12/\n\x13position_covariance\x18\x06 \x01(\x0b\x32\x12.kevin.Covariance6\x12\'\n\x04type\x18\x07 \x01(\x0e\x32\x19.kevin.PositionCovariance*\x92\x01\n\x12PositionCovariance\x12\x1b\n\x17\x43OVARIANCE_TYPE_UNKNOWN\x10\x00\x12 \n\x1c\x43OVARIANCE_TYPE_APPROXIMATED\x10\x01\x12\"\n\x1e\x43OVARIANCE_TYPE_DIAGONAL_KNOWN\x10\x02\x12\x19\n\x15\x43OVARIANCE_TYPE_KNOWN\x10\x03*E\n\tStatusFix\x12\x0e\n\nSTATUS_FIX\x10\x00\x12\x13\n\x0fSTATUS_SBAS_FIX\x10\x01\x12\x13\n\x0fSTATUS_GBAS_FIX\x10\x02*r\n\x0bServiceType\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x00\x12\x0f\n\x0bSERVICE_GPS\x10\x01\x12\x13\n\x0fSERVICE_GLONASS\x10\x02\x12\x13\n\x0fSERVICE_COMPASS\x10\x04\x12\x13\n\x0fSERVICE_GALILEO\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'satnav_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSITIONCOVARIANCE']._serialized_start=367
  _globals['_POSITIONCOVARIANCE']._serialized_end=513
  _globals['_STATUSFIX']._serialized_start=515
  _globals['_STATUSFIX']._serialized_end=584
  _globals['_SERVICETYPE']._serialized_start=586
  _globals['_SERVICETYPE']._serialized_end=700
  _globals['_NAVSATSTATUS']._serialized_start=55
  _globals['_NAVSATSTATUS']._serialized_end=140
  _globals['_SATNAV']._serialized_start=143
  _globals['_SATNAV']._serialized_end=364
# @@protoc_insertion_point(module_scope)
