# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wrench.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'wrench.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vector3_pb2 as vector3__pb2
import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwrench.proto\x12\x05kevin\x1a\rvector3.proto\x1a\x0cheader.proto\"G\n\x06Wrench\x12\x1d\n\x05\x66orce\x18\x01 \x01(\x0b\x32\x0e.kevin.Vector3\x12\x1e\n\x06torque\x18\x02 \x01(\x0b\x32\x0e.kevin.Vector3\"m\n\rWrenchStamped\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.kevin.Header\x12\x1d\n\x05\x66orce\x18\x02 \x01(\x0b\x32\x0e.kevin.Vector3\x12\x1e\n\x06torque\x18\x03 \x01(\x0b\x32\x0e.kevin.Vector3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wrench_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRENCH']._serialized_start=52
  _globals['_WRENCH']._serialized_end=123
  _globals['_WRENCHSTAMPED']._serialized_start=125
  _globals['_WRENCHSTAMPED']._serialized_end=234
# @@protoc_insertion_point(module_scope)
