// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: math_msgs.proto
// Protobuf C++ Version: 5.29.3

#ifndef math_5fmsgs_2eproto_2epb_2eh
#define math_5fmsgs_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_math_5fmsgs_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_math_5fmsgs_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_math_5fmsgs_2eproto;
namespace kevin {
class Covariance3;
struct Covariance3DefaultTypeInternal;
extern Covariance3DefaultTypeInternal _Covariance3_default_instance_;
class Covariance6;
struct Covariance6DefaultTypeInternal;
extern Covariance6DefaultTypeInternal _Covariance6_default_instance_;
}  // namespace kevin
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace kevin {

// ===================================================================


// -------------------------------------------------------------------

class Covariance6 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kevin.Covariance6) */ {
 public:
  inline Covariance6() : Covariance6(nullptr) {}
  ~Covariance6() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Covariance6* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Covariance6));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Covariance6(
      ::google::protobuf::internal::ConstantInitialized);

  inline Covariance6(const Covariance6& from) : Covariance6(nullptr, from) {}
  inline Covariance6(Covariance6&& from) noexcept
      : Covariance6(nullptr, std::move(from)) {}
  inline Covariance6& operator=(const Covariance6& from) {
    CopyFrom(from);
    return *this;
  }
  inline Covariance6& operator=(Covariance6&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Covariance6& default_instance() {
    return *internal_default_instance();
  }
  static inline const Covariance6* internal_default_instance() {
    return reinterpret_cast<const Covariance6*>(
        &_Covariance6_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Covariance6& a, Covariance6& b) { a.Swap(&b); }
  inline void Swap(Covariance6* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Covariance6* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Covariance6* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Covariance6>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Covariance6& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Covariance6& from) { Covariance6::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Covariance6* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kevin.Covariance6"; }

 protected:
  explicit Covariance6(::google::protobuf::Arena* arena);
  Covariance6(::google::protobuf::Arena* arena, const Covariance6& from);
  Covariance6(::google::protobuf::Arena* arena, Covariance6&& from) noexcept
      : Covariance6(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXxFieldNumber = 1,
    kYyFieldNumber = 2,
    kZzFieldNumber = 3,
    kXyFieldNumber = 4,
    kXzFieldNumber = 5,
    kYzFieldNumber = 6,
  };
  // double xx = 1;
  void clear_xx() ;
  double xx() const;
  void set_xx(double value);

  private:
  double _internal_xx() const;
  void _internal_set_xx(double value);

  public:
  // double yy = 2;
  void clear_yy() ;
  double yy() const;
  void set_yy(double value);

  private:
  double _internal_yy() const;
  void _internal_set_yy(double value);

  public:
  // double zz = 3;
  void clear_zz() ;
  double zz() const;
  void set_zz(double value);

  private:
  double _internal_zz() const;
  void _internal_set_zz(double value);

  public:
  // double xy = 4;
  void clear_xy() ;
  double xy() const;
  void set_xy(double value);

  private:
  double _internal_xy() const;
  void _internal_set_xy(double value);

  public:
  // double xz = 5;
  void clear_xz() ;
  double xz() const;
  void set_xz(double value);

  private:
  double _internal_xz() const;
  void _internal_set_xz(double value);

  public:
  // double yz = 6;
  void clear_yz() ;
  double yz() const;
  void set_yz(double value);

  private:
  double _internal_yz() const;
  void _internal_set_yz(double value);

  public:
  // @@protoc_insertion_point(class_scope:kevin.Covariance6)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Covariance6& from_msg);
    double xx_;
    double yy_;
    double zz_;
    double xy_;
    double xz_;
    double yz_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_math_5fmsgs_2eproto;
};
// -------------------------------------------------------------------

class Covariance3 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kevin.Covariance3) */ {
 public:
  inline Covariance3() : Covariance3(nullptr) {}
  ~Covariance3() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Covariance3* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Covariance3));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Covariance3(
      ::google::protobuf::internal::ConstantInitialized);

  inline Covariance3(const Covariance3& from) : Covariance3(nullptr, from) {}
  inline Covariance3(Covariance3&& from) noexcept
      : Covariance3(nullptr, std::move(from)) {}
  inline Covariance3& operator=(const Covariance3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Covariance3& operator=(Covariance3&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Covariance3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Covariance3* internal_default_instance() {
    return reinterpret_cast<const Covariance3*>(
        &_Covariance3_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Covariance3& a, Covariance3& b) { a.Swap(&b); }
  inline void Swap(Covariance3* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Covariance3* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Covariance3* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Covariance3>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Covariance3& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Covariance3& from) { Covariance3::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Covariance3* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kevin.Covariance3"; }

 protected:
  explicit Covariance3(::google::protobuf::Arena* arena);
  Covariance3(::google::protobuf::Arena* arena, const Covariance3& from);
  Covariance3(::google::protobuf::Arena* arena, Covariance3&& from) noexcept
      : Covariance3(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXxFieldNumber = 1,
    kYyFieldNumber = 2,
    kZzFieldNumber = 3,
  };
  // double xx = 1;
  void clear_xx() ;
  double xx() const;
  void set_xx(double value);

  private:
  double _internal_xx() const;
  void _internal_set_xx(double value);

  public:
  // double yy = 2;
  void clear_yy() ;
  double yy() const;
  void set_yy(double value);

  private:
  double _internal_yy() const;
  void _internal_set_yy(double value);

  public:
  // double zz = 3;
  void clear_zz() ;
  double zz() const;
  void set_zz(double value);

  private:
  double _internal_zz() const;
  void _internal_set_zz(double value);

  public:
  // @@protoc_insertion_point(class_scope:kevin.Covariance3)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Covariance3& from_msg);
    double xx_;
    double yy_;
    double zz_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_math_5fmsgs_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Covariance3

// double xx = 1;
inline void Covariance3::clear_xx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xx_ = 0;
}
inline double Covariance3::xx() const {
  // @@protoc_insertion_point(field_get:kevin.Covariance3.xx)
  return _internal_xx();
}
inline void Covariance3::set_xx(double value) {
  _internal_set_xx(value);
  // @@protoc_insertion_point(field_set:kevin.Covariance3.xx)
}
inline double Covariance3::_internal_xx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.xx_;
}
inline void Covariance3::_internal_set_xx(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xx_ = value;
}

// double yy = 2;
inline void Covariance3::clear_yy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yy_ = 0;
}
inline double Covariance3::yy() const {
  // @@protoc_insertion_point(field_get:kevin.Covariance3.yy)
  return _internal_yy();
}
inline void Covariance3::set_yy(double value) {
  _internal_set_yy(value);
  // @@protoc_insertion_point(field_set:kevin.Covariance3.yy)
}
inline double Covariance3::_internal_yy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.yy_;
}
inline void Covariance3::_internal_set_yy(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yy_ = value;
}

// double zz = 3;
inline void Covariance3::clear_zz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.zz_ = 0;
}
inline double Covariance3::zz() const {
  // @@protoc_insertion_point(field_get:kevin.Covariance3.zz)
  return _internal_zz();
}
inline void Covariance3::set_zz(double value) {
  _internal_set_zz(value);
  // @@protoc_insertion_point(field_set:kevin.Covariance3.zz)
}
inline double Covariance3::_internal_zz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.zz_;
}
inline void Covariance3::_internal_set_zz(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.zz_ = value;
}

// -------------------------------------------------------------------

// Covariance6

// double xx = 1;
inline void Covariance6::clear_xx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xx_ = 0;
}
inline double Covariance6::xx() const {
  // @@protoc_insertion_point(field_get:kevin.Covariance6.xx)
  return _internal_xx();
}
inline void Covariance6::set_xx(double value) {
  _internal_set_xx(value);
  // @@protoc_insertion_point(field_set:kevin.Covariance6.xx)
}
inline double Covariance6::_internal_xx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.xx_;
}
inline void Covariance6::_internal_set_xx(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xx_ = value;
}

// double yy = 2;
inline void Covariance6::clear_yy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yy_ = 0;
}
inline double Covariance6::yy() const {
  // @@protoc_insertion_point(field_get:kevin.Covariance6.yy)
  return _internal_yy();
}
inline void Covariance6::set_yy(double value) {
  _internal_set_yy(value);
  // @@protoc_insertion_point(field_set:kevin.Covariance6.yy)
}
inline double Covariance6::_internal_yy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.yy_;
}
inline void Covariance6::_internal_set_yy(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yy_ = value;
}

// double zz = 3;
inline void Covariance6::clear_zz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.zz_ = 0;
}
inline double Covariance6::zz() const {
  // @@protoc_insertion_point(field_get:kevin.Covariance6.zz)
  return _internal_zz();
}
inline void Covariance6::set_zz(double value) {
  _internal_set_zz(value);
  // @@protoc_insertion_point(field_set:kevin.Covariance6.zz)
}
inline double Covariance6::_internal_zz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.zz_;
}
inline void Covariance6::_internal_set_zz(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.zz_ = value;
}

// double xy = 4;
inline void Covariance6::clear_xy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xy_ = 0;
}
inline double Covariance6::xy() const {
  // @@protoc_insertion_point(field_get:kevin.Covariance6.xy)
  return _internal_xy();
}
inline void Covariance6::set_xy(double value) {
  _internal_set_xy(value);
  // @@protoc_insertion_point(field_set:kevin.Covariance6.xy)
}
inline double Covariance6::_internal_xy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.xy_;
}
inline void Covariance6::_internal_set_xy(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xy_ = value;
}

// double xz = 5;
inline void Covariance6::clear_xz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xz_ = 0;
}
inline double Covariance6::xz() const {
  // @@protoc_insertion_point(field_get:kevin.Covariance6.xz)
  return _internal_xz();
}
inline void Covariance6::set_xz(double value) {
  _internal_set_xz(value);
  // @@protoc_insertion_point(field_set:kevin.Covariance6.xz)
}
inline double Covariance6::_internal_xz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.xz_;
}
inline void Covariance6::_internal_set_xz(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xz_ = value;
}

// double yz = 6;
inline void Covariance6::clear_yz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yz_ = 0;
}
inline double Covariance6::yz() const {
  // @@protoc_insertion_point(field_get:kevin.Covariance6.yz)
  return _internal_yz();
}
inline void Covariance6::set_yz(double value) {
  _internal_set_yz(value);
  // @@protoc_insertion_point(field_set:kevin.Covariance6.yz)
}
inline double Covariance6::_internal_yz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.yz_;
}
inline void Covariance6::_internal_set_yz(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yz_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace kevin


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // math_5fmsgs_2eproto_2epb_2eh
